baseURL = "https://llm-pt-ibm.github.io/"
languageCode = 'pt-br'
theme = 'Kiera'
title = 'LLM IBM UFCG'
pagination.pagerSize = 10
copyright = "IBM & UFCG - 2025"

[params]
  tagline = "Blog com relatórios periódicos das tarefas realizadas."
  disableDarkModeCSS = true
  customCSS = ["css/custom.css", "css/font.css"]
  site_logo = "/llm_ibm_blog.github.io/site_logo.png"
  [params.assets]
    favicon = 'favicon.ico'
    favicon16x16 = 'favicon-16x16.png'
    favicon32x32 = 'favicon-32x32.png'
    appletouchicon = 'apple-touch-icon.png'

[menu]
  [[menu.main]]
    name = "Equipe"
    url = "/team/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 2

  [[menu.main]]
    name = "Início"
    url = "/"
    weight = 1

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [[module.mounts]]
  source = 'static'
  target = 'assets'